import torch
from torch import nn
import pytorch_lightning as pl
import torch.nn.functional as F

from ..layers import PlaneConv, PlaneConvTranspose
from ..util import get_activation_by_name, parse_conv_spec, load_geom_mask


class Decoder(pl.LightningModule):
    """DarkSHINE xyz decoder.

    Latent (N, ch_in, h, w) -> transpose plane-convs -> logits (N, depth=11, 48, 48).
    The final activation is a MASKED voxel-softmax: logits at padding cells (the
    ~8% of the 43x43 grid that are not real crystals, plus the 43->48 padding
    border) are set to -inf so they receive exactly zero probability and cannot
    steal mass from real cells. The normalised output therefore sums to 1 over the
    real crystals only. We then crop 48 -> 43 (dropping the zero-probability
    border) to return pixels_U_pred (N, 11, 43, 43).

    The geometry mask is fixed (identical for every shower) and loaded from
    `mask_path`; it is the承重件 that makes generation well-defined.
    """
    def __init__(self, *,
            ch_in,
            ch_out,                # number of calorimeter layers (depth) = 11
            conv_spec,
            cond_dim=1,
            activation='swish',
            output_activation='voxel_softmax',   # kept for config compat; masked softmax is always used
            mask_path='DarkSHINE_data/geom_mask.npy',
            pad_to=48,             # internal padded plane size
            out_size=43,           # cropped output plane size
            learn_R=False,
            ch_init=-1,
            # accepted for config-passthru compatibility but unused in xyz:
            z_pad=None, z_padding_strategy=None, R_activation='softplus', R_trim=1e-2,
            ):
        super().__init__()

        assert not learn_R, "R is generated by the stage-2 GPT, not the decoder."
        self.ch_in = ch_in
        self.ch_out = ch_out
        self.pad_to = pad_to
        self.out_size = out_size

        if cond_dim not in (0, 1):
            raise NotImplementedError("cond_dim>1 not handled yet.")
        self.register_buffer('cond_dim', torch.tensor(cond_dim))

        # fixed geometry mask, channels-first (depth, x, y) = (11, 43, 43),
        # padded to (11, pad_to, pad_to) with False in the border.
        mask = load_geom_mask(mask_path)               # (11, 43, 43) bool
        pad = pad_to - mask.shape[-1]
        if pad > 0:
            mask = F.pad(mask, (0, pad, 0, pad), value=False)
        # fixed constant -> persistent=False (recomputed from mask_path each init)
        self.register_buffer('mask', mask.contiguous(), persistent=False)  # (11, pad_to, pad_to) bool

        activation_class = get_activation_by_name(activation)

        self.dec_layers = nn.Sequential()
        w_in = ch_in + cond_dim
        w_out = ch_init
        self._adaptive_layer = None
        for spec in conv_spec:
            ltype, *spec = spec.split(':')
            ltype = ltype.strip()
            k, s, p, w_out = parse_conv_spec(':'.join(spec), w_out)
            if ltype == 'pconvT':
                conv = PlaneConvTranspose(w_in, w_out, k=k, stride=s, pad_z=p)
            elif ltype == 'pconv':
                conv = PlaneConv(w_in, w_out, k=k, stride=s, pad_z=p)
            else:
                raise AssertionError(f"xyz decoder supports 'pconvT'/'pconv', got {ltype!r}")
            w_in = w_out
            self.dec_layers.append(conv)
            self.dec_layers.append(activation_class())
            self._adaptive_layer = conv

        # 1x1 conv to the depth channel dim (logits)
        self.dec_layers.append(PlaneConv(w_in, ch_out, k=(1, 1), stride=(1, 1), pad_z=False))

    def get_adaptive_layer_weights(self):
        return self._adaptive_layer.weights

    def masked_voxel_softmax(self, logits):
        # logits ~ (N, depth, pad_to, pad_to). Softmax over all real voxels per shower.
        mask = self.mask[None]                                  # (1, 11, P, P)
        neg_inf = torch.finfo(logits.dtype).min
        logits = torch.where(mask, logits, torch.full_like(logits, neg_inf))
        x = torch.exp(logits.double())
        x = x * mask                                            # hard-zero padding (guards against all -inf rows)
        denom = x.sum(axis=(-1, -2, -3), keepdims=True)
        return (x / denom).float()

    def forward(self, x, cond=None):
        # x ~ (N, ch_in, h, w); cond ~ (N, 1)
        if self.cond_dim > 0:
            xc = cond[:, None, None].expand((-1, -1, x.shape[-2], x.shape[-1]))
            x = torch.concat([x, xc], axis=-3)

        pix = x
        for layer in self.dec_layers:
            pix = layer(pix)                                    # -> (N, depth, pad_to, pad_to) logits

        pix = self.masked_voxel_softmax(pix)                    # sums to 1 over real cells
        pix = pix[..., :self.out_size, :self.out_size]          # crop pad_to -> 43

        return {'pixels_U_pred': pix}
