import torch
from torch import nn
import pytorch_lightning as pl
import torch.nn.functional as F

from ..util import get_activation_by_name, parse_conv_spec, conv_padding, load_geom_mask


class Decoder(pl.LightningModule):
    """DarkSHINE xyz decoder.

    Latent (N, ch_in, h, w) -> transpose plane-convs -> logits (N, depth=11, 48, 48).
    The final activation is a MASKED voxel-softmax: logits at padding cells (the
    ~8% of the 43x43 grid that are not real crystals, plus the 43->48 padding
    border) are set to -inf so they receive exactly zero probability and cannot
    steal mass from real cells. The normalised output therefore sums to 1 over the
    real crystals only. We then crop 48 -> 43 (dropping the zero-probability
    border) to return pixels_U_pred (N, 11, 43, 43).

    The geometry mask is fixed (identical for every shower) and loaded from
    `mask_path`; it is the承重件 that makes generation well-defined.
    """
    def __init__(self, *,
            ch_in,
            ch_out,                # number of calorimeter layers (depth) = 11
            conv_spec,
            cond_dim=1,
            activation='swish',
            output_activation='voxel_softmax',   # kept for config compat; masked softmax is always used
            mask_path='DarkSHINE_data/geom_mask.npy',
            pad_to=48,             # internal padded plane size
            out_size=43,           # cropped output plane size
            learn_R=False,
            ch_init=-1,
            # accepted for config-passthru compatibility but unused in xyz:
            z_pad=None, z_padding_strategy=None, R_activation='softplus', R_trim=1e-2,
            ):
        super().__init__()

        assert not learn_R, "R is generated by the stage-2 GPT, not the decoder."
        self.ch_in = ch_in
        self.ch_out = ch_out
        self.pad_to = pad_to
        self.out_size = out_size

        if cond_dim not in (0, 1):
            raise NotImplementedError("cond_dim>1 not handled yet.")
        self.register_buffer('cond_dim', torch.tensor(cond_dim))

        # fixed geometry mask, channels-first (depth, x, y) = (11, 43, 43),
        # padded to (11, pad_to, pad_to) with False in the border.
        mask = load_geom_mask(mask_path)               # (11, 43, 43) bool
        pad = pad_to - mask.shape[-1]
        if pad > 0:
            mask = F.pad(mask, (0, pad, 0, pad), value=False)
        # fixed constant -> persistent=False (recomputed from mask_path each init)
        self.register_buffer('mask', mask.contiguous(), persistent=False)  # (11, pad_to, pad_to) bool

        # Output parameterisation over the real crystals. All three sum to 1 over
        # real cells; they differ in whether they can emit EXACT zeros:
        #   'voxel_softmax' (default) - dense & smooth (original); always leaves a
        #       non-zero halo, so the predicted occupancy is necessarily too high
        #       and the U-space recon L1 vs the genuinely-sparse truth has an
        #       irreducible floor.
        #   'sparsemax'     - Euclidean projection onto the simplex (Martins &
        #       Astudillo 2016); emits true zeros, gradient has no sqrt singularity.
        #   'relu_norm'     - relu(logits) renormalised; simplest sparse option.
        # The network learns to scale the logits, which sets how sparse the output
        # is -> a learnable occupancy knob (the energy head's own version of the
        # hit/no-hit gate).
        assert output_activation in ('voxel_softmax', 'sparsemax', 'relu_norm'), \
            f"unknown output_activation {output_activation!r}"
        self.output_activation = output_activation
        # flat indices of the real cells over (depth, pad_to, pad_to), matching the
        # flatten(start_dim=1) order used below -> gather/scatter for the sparse path.
        real_idx = self.mask.reshape(-1).nonzero(as_tuple=False).squeeze(1)
        self.register_buffer('real_idx', real_idx, persistent=False)

        activation_class = get_activation_by_name(activation)

        self.dec_layers = nn.Sequential()
        w_in = ch_in + cond_dim
        w_out = ch_init
        self._adaptive_layer = None
        for spec in conv_spec:
            ltype, *spec = spec.split(':')
            ltype = ltype.strip()
            k, s, p, w_out = parse_conv_spec(':'.join(spec), w_out)
            if ltype == 'pconvT':
                conv = nn.ConvTranspose2d(w_in, w_out, kernel_size=k, stride=s, padding=conv_padding(k, p))
            elif ltype == 'pconv':
                conv = nn.Conv2d(w_in, w_out, kernel_size=k, stride=s, padding=conv_padding(k, p))
            else:
                raise AssertionError(f"xyz decoder supports 'pconvT'/'pconv', got {ltype!r}")
            w_in = w_out
            self.dec_layers.append(conv)
            self.dec_layers.append(activation_class())
            self._adaptive_layer = conv

        # 1x1 conv to the depth channel dim (energy-shape logits). Kept as the last
        # element of dec_layers so its checkpoint key is unchanged (the energy model
        # loads cleanly when fine-tuning with the new hit head).
        self.dec_layers.append(nn.Conv2d(w_in, ch_out, kernel_size=(1, 1)))

        # Hit/no-hit head (sparse-occupancy modelling): a parallel 1x1 conv on the
        # same final features producing per-cell hit logits. Trained with a masked,
        # class-imbalance-weighted BCE; at inference a hard gate sigmoid(logits)>thr
        # masks the energy softmax so the over-broad soft tail is removed. See
        # VQModel._apply_hit_gate / CombinedLoss (hit_weight).
        self.hit_head = nn.Conv2d(w_in, ch_out, kernel_size=(1, 1))

    def get_adaptive_layer_weights(self):
        return self._adaptive_layer.weight

    def masked_voxel_softmax(self, logits):
        # logits ~ (N, depth, pad_to, pad_to). Softmax over all real voxels per shower.
        mask = self.mask[None]                                  # (1, 11, P, P)
        neg_inf = torch.finfo(logits.dtype).min
        logits = torch.where(mask, logits, torch.full_like(logits, neg_inf))
        probs = F.softmax(logits.flatten(start_dim=1).double(), dim=1)
        probs = probs.reshape_as(logits).to(logits.dtype) * mask
        return probs.float()

    @staticmethod
    def _sparsemax(z):
        # z ~ (N, K): Euclidean projection of each row onto the probability simplex
        # (Martins & Astudillo 2016). Returns p>=0, sum_k p=1, with exact zeros below
        # the threshold tau. Autograd through sort/cumsum/gather/clamp reproduces the
        # sparsemax Jacobian (delta_ij - 1/|support| on the support) with no singularity.
        z_sorted, _ = torch.sort(z, dim=1, descending=True)
        z_cumsum = z_sorted.cumsum(dim=1)
        K = z.shape[1]
        k_arr = torch.arange(1, K + 1, device=z.device, dtype=z.dtype)  # (K,)
        support = (1.0 + k_arr * z_sorted) > z_cumsum                   # (N, K) bool
        k_z = support.sum(dim=1, keepdim=True)                          # (N, 1) long, >=1
        tau = (z_cumsum.gather(1, k_z - 1) - 1.0) / k_z.to(z.dtype)     # (N, 1)
        return torch.clamp(z - tau, min=0.0)

    @staticmethod
    def _relu_norm(z, eps=1e-12):
        # z ~ (N, K): relu then renormalise to sum 1 over real cells. Emits exact zeros
        # where logits <= 0. Fallback to uniform for the (rare) all-non-positive row so
        # the output stays a valid distribution instead of 0/0.
        r = torch.relu(z)
        s = r.sum(dim=1, keepdim=True)
        uniform = torch.full_like(r, 1.0 / z.shape[1])
        return torch.where(s > eps, r / s.clamp(min=eps), uniform)

    def normalize_output(self, logits):
        # logits ~ (N, depth, pad_to, pad_to) -> distribution summing to 1 over real cells.
        if self.output_activation == 'voxel_softmax':
            return self.masked_voxel_softmax(logits)
        # sparse paths: gather real cells -> simplex projection -> scatter back, so
        # padding cells stay exactly 0 (the 43->48 border + the ~8% intra-grid padding).
        flat = logits.reshape(logits.shape[0], -1)              # (N, depth*P*P)
        z = flat[:, self.real_idx]                              # (N, K)
        if self.output_activation == 'sparsemax':
            p = self._sparsemax(z)
        else:  # 'relu_norm'
            p = self._relu_norm(z)
        out = torch.zeros_like(flat).index_copy(1, self.real_idx, p)
        return out.reshape_as(logits).float()

    def forward(self, x, cond=None):
        # x ~ (N, ch_in, h, w); cond ~ (N, 1)
        if self.cond_dim > 0:
            xc = cond[:, None, None].expand((-1, -1, x.shape[-2], x.shape[-1]))
            x = torch.concat([x, xc], axis=-3)

        feat = x
        layers = list(self.dec_layers)
        for layer in layers[:-1]:                               # body up to the last activation
            feat = layer(feat)
        energy_logits = layers[-1](feat)                        # (N, depth, pad_to, pad_to)
        # detach the shared features: the hit head trains only its own 1x1 conv and
        # never perturbs the (already-trained) energy reconstruction.
        hit_logits = self.hit_head(feat.detach())               # (N, depth, pad_to, pad_to)

        pix = self.normalize_output(energy_logits)              # sums to 1 over real cells
        o = self.out_size
        pix = pix[..., :o, :o]                                  # crop pad_to -> 43
        hit_logits = hit_logits[..., :o, :o]                    # crop; downstream masks to real cells

        return {'pixels_U_pred': pix, 'pixels_hit_logits': hit_logits}
