import torch
from torch import nn
import pytorch_lightning as pl
import torch.nn.functional as F

from ..util import get_activation_by_name, parse_conv_spec, conv_padding, load_geom_mask


class Decoder(pl.LightningModule):
    """DarkSHINE xyz decoder.

    Latent (N, ch_in, h, w) -> transpose plane-convs -> logits (N, depth=11, 48, 48).
    The final activation is a MASKED voxel-softmax: logits at padding cells (the
    ~8% of the 43x43 grid that are not real crystals, plus the 43->48 padding
    border) are set to -inf so they receive exactly zero probability and cannot
    steal mass from real cells. The normalised output therefore sums to 1 over the
    real crystals only. We then crop 48 -> 43 (dropping the zero-probability
    border) to return pixels_U_pred (N, 11, 43, 43).

    The geometry mask is fixed (identical for every shower) and loaded from
    `mask_path`; it is the承重件 that makes generation well-defined.
    """
    def __init__(self, *,
            ch_in,
            ch_out,                # number of calorimeter layers (depth) = 11
            conv_spec,
            cond_dim=1,
            activation='swish',
            output_activation='voxel_softmax',   # kept for config compat; masked softmax is always used
            mask_path='DarkSHINE_data/geom_mask.npy',
            pad_to=48,             # internal padded plane size
            out_size=43,           # cropped output plane size
            learn_R=False,
            ch_init=-1,
            # accepted for config-passthru compatibility but unused in xyz:
            z_pad=None, z_padding_strategy=None, R_activation='softplus', R_trim=1e-2,
            ):
        super().__init__()

        assert not learn_R, "R is generated by the stage-2 GPT, not the decoder."
        self.ch_in = ch_in
        self.ch_out = ch_out
        self.pad_to = pad_to
        self.out_size = out_size

        if cond_dim not in (0, 1):
            raise NotImplementedError("cond_dim>1 not handled yet.")
        self.register_buffer('cond_dim', torch.tensor(cond_dim))

        # fixed geometry mask, channels-first (depth, x, y) = (11, 43, 43),
        # padded to (11, pad_to, pad_to) with False in the border.
        mask = load_geom_mask(mask_path)               # (11, 43, 43) bool
        pad = pad_to - mask.shape[-1]
        if pad > 0:
            mask = F.pad(mask, (0, pad, 0, pad), value=False)
        # fixed constant -> persistent=False (recomputed from mask_path each init)
        self.register_buffer('mask', mask.contiguous(), persistent=False)  # (11, pad_to, pad_to) bool

        activation_class = get_activation_by_name(activation)

        self.dec_layers = nn.Sequential()
        w_in = ch_in + cond_dim
        w_out = ch_init
        self._adaptive_layer = None
        for spec in conv_spec:
            ltype, *spec = spec.split(':')
            ltype = ltype.strip()
            k, s, p, w_out = parse_conv_spec(':'.join(spec), w_out)
            if ltype == 'pconvT':
                conv = nn.ConvTranspose2d(w_in, w_out, kernel_size=k, stride=s, padding=conv_padding(k, p))
            elif ltype == 'pconv':
                conv = nn.Conv2d(w_in, w_out, kernel_size=k, stride=s, padding=conv_padding(k, p))
            else:
                raise AssertionError(f"xyz decoder supports 'pconvT'/'pconv', got {ltype!r}")
            w_in = w_out
            self.dec_layers.append(conv)
            self.dec_layers.append(activation_class())
            self._adaptive_layer = conv

        # 1x1 conv to the depth channel dim (energy-shape logits). Kept as the last
        # element of dec_layers so its checkpoint key is unchanged (the energy model
        # loads cleanly when fine-tuning with the new hit head).
        self.dec_layers.append(nn.Conv2d(w_in, ch_out, kernel_size=(1, 1)))

        # Hit/no-hit head (sparse-occupancy modelling): a parallel 1x1 conv on the
        # same final features producing per-cell hit logits. Trained with a masked,
        # class-imbalance-weighted BCE; at inference a hard gate sigmoid(logits)>thr
        # masks the energy softmax so the over-broad soft tail is removed. See
        # VQModel._apply_hit_gate / CombinedLoss (hit_weight).
        self.hit_head = nn.Conv2d(w_in, ch_out, kernel_size=(1, 1))

    def get_adaptive_layer_weights(self):
        return self._adaptive_layer.weight

    def masked_voxel_softmax(self, logits):
        # logits ~ (N, depth, pad_to, pad_to). Softmax over all real voxels per shower.
        mask = self.mask[None]                                  # (1, 11, P, P)
        neg_inf = torch.finfo(logits.dtype).min
        logits = torch.where(mask, logits, torch.full_like(logits, neg_inf))
        probs = F.softmax(logits.flatten(start_dim=1).double(), dim=1)
        probs = probs.reshape_as(logits).to(logits.dtype) * mask
        return probs.float()

    def forward(self, x, cond=None):
        # x ~ (N, ch_in, h, w); cond ~ (N, 1)
        if self.cond_dim > 0:
            xc = cond[:, None, None].expand((-1, -1, x.shape[-2], x.shape[-1]))
            x = torch.concat([x, xc], axis=-3)

        feat = x
        layers = list(self.dec_layers)
        for layer in layers[:-1]:                               # body up to the last activation
            feat = layer(feat)
        energy_logits = layers[-1](feat)                        # (N, depth, pad_to, pad_to)
        # detach the shared features: the hit head trains only its own 1x1 conv and
        # never perturbs the (already-trained) energy reconstruction.
        hit_logits = self.hit_head(feat.detach())               # (N, depth, pad_to, pad_to)

        pix = self.masked_voxel_softmax(energy_logits)          # sums to 1 over real cells
        o = self.out_size
        pix = pix[..., :o, :o]                                  # crop pad_to -> 43
        hit_logits = hit_logits[..., :o, :o]                    # crop; downstream masks to real cells

        return {'pixels_U_pred': pix, 'pixels_hit_logits': hit_logits}
